<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Hambaft.Domain\Hambaft.Domain.csproj" />
    <PackageReference Include="Qyl27.Ink.Engine" />
  </ItemGroup>
</Project>
