<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
</PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hambaft.Application\Hambaft.Application.csproj" />
    <ProjectReference Include="..\Hambaft.Domain\Hambaft.Domain.csproj" />
    <ProjectReference Include="..\Hambaft.Narrative.Ink\Hambaft.Narrative.Ink.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Marten" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Npgsql" />
  </ItemGroup>

</Project>
