using Hambaft.Application;
using Hambaft.Domain;
using Marten.Events.Aggregation;

namespace Hambaft.Infrastructure.Persistence;

public sealed partial class SessionExperienceProjection : SingleStreamProjection<SessionExperienceView,Guid>
{
    public SessionExperienceProjection()=>Name="SessionExperience";
    public SessionExperienceView Create(SessionCreated e)=>new(e.Id,SessionStatus.Created,[],[],[],[],[],1,e.StoryPackageId,e.StoryVersion,e.ContentHash,null,[],[],e.DifficultyId,0,[],[],[],[],[]);
    public SessionExperienceView Apply(TeamAdded e,SessionExperienceView v)=>v with { Status=v.Status==SessionStatus.Created?SessionStatus.Lobby:v.Status,Teams=v.Teams.Append(new Team(e.TeamId,v.Id,e.DisplayName,e.PairingCodeHash,null,e.Metadata.OccurredAtUtc)).ToList(),StateVersion=v.StateVersion+1 };
    public SessionExperienceView Apply(WorldEntityCreated e,SessionExperienceView v)=>v with { Entities=v.Entities.Append(new(e.EntityId,v.Id,e.DefinitionId,e.DisplayName,e.ControllerType,null,e.BehaviorProfileId,e.Status)).ToList(),StateVersion=v.StateVersion+1 };
    public SessionExperienceView Apply(EntityAssignedToTeam e,SessionExperienceView v)=>v with { Teams=v.Teams.Select(x=>x.Id==e.TeamId?x with { ControlledEntityId=e.EntityId }:x).ToList(),Entities=v.Entities.Select(x=>x.Id==e.EntityId?x with { ControlledByTeamId=e.TeamId,Status=EntityStatus.Active }:x).ToList(),StateVersion=v.StateVersion+1 };
    public SessionExperienceView Apply(InitialMetricSet e,SessionExperienceView v)=>v with { Metrics=Upsert(v.Metrics,new(e.Scope,e.ScopeId,e.MetricKey,e.NumericValue)),StateVersion=v.StateVersion+1 };
    public SessionExperienceView Apply(InitialMemoryAdded e,SessionExperienceView v)=>v with { Memories=v.Memories.Append(new(e.Scope,e.ScopeId,e.Key,e.OptionalJsonValue,e.Visibility,e.Metadata.OccurredAtUtc)).ToList(),StateVersion=v.StateVersion+1 };
    public SessionExperienceView Apply(InitialRelationshipSet e,SessionExperienceView v)=>v with { Relationships=Upsert(v.Relationships,new(e.SourceEntityId,e.TargetEntityId,e.RelationshipKey,e.NumericValue)),StateVersion=v.StateVersion+1 };
    public SessionExperienceView Apply(SessionStarted _,SessionExperienceView v)=>v with { Status=SessionStatus.Running,Entities=v.Entities.Select(x=>x with { Status=EntityStatus.Active }).ToList(),StateVersion=v.StateVersion+1 };
    public SessionExperienceView Apply(SessionPaused _,SessionExperienceView v)=>v with { Status=SessionStatus.Paused,StateVersion=v.StateVersion+1 }; public SessionExperienceView Apply(SessionResumed _,SessionExperienceView v)=>v with { Status=SessionStatus.Running,StateVersion=v.StateVersion+1 }; public SessionExperienceView Apply(SessionCancelled _,SessionExperienceView v)=>v with { Status=SessionStatus.Cancelled,StateVersion=v.StateVersion+1 };
    public SessionExperienceView Apply(NarrativeInitialized e,SessionExperienceView v)=>v with { CurrentCheckpointId=e.CheckpointId,StateVersion=v.StateVersion+1 };
    public SessionExperienceView Apply(StoryletAssigned e,SessionExperienceView v)=>v with { StoryletAssignments=v.StoryletAssignments.Append(SessionStateProjection.ToAssignment(e)).ToList(),StateVersion=v.StateVersion+1 };
    public SessionExperienceView Apply(StoryChoiceSubmitted e,SessionExperienceView v)=>v with { StoryletAssignments=SessionStateProjection.Respond(v.StoryletAssignments,e.AssignmentId),SubmittedChoices=v.SubmittedChoices.Append(SessionStateProjection.ToChoice(e)).ToList(),StateVersion=v.StateVersion+1 };
    public SessionExperienceView Apply(NarrativeCheckpointResolved e,SessionExperienceView v)=>v with { CurrentCheckpointId=e.NextCheckpointId,CheckpointResolutionNumber=v.CheckpointResolutionNumber+1,StoryletAssignments=SessionStateProjection.Resolve(v.StoryletAssignments,e.ResolvedAssignmentIds),StateVersion=v.StateVersion+1 };
    public SessionExperienceView Apply(MetricChanged e,SessionExperienceView v)=>v with { Metrics=Upsert(v.Metrics,new(e.Scope,e.ScopeId,e.MetricKey,e.NewValue)),StateVersion=v.StateVersion+1 };
    public SessionExperienceView Apply(MetricSet e,SessionExperienceView v)=>v with { Metrics=Upsert(v.Metrics,new(e.Scope,e.ScopeId,e.MetricKey,e.NewValue)),StateVersion=v.StateVersion+1 };
    public SessionExperienceView Apply(StoryMemoryAdded e,SessionExperienceView v)=>v with { Memories=v.Memories.Append(new(e.Scope,e.ScopeId,e.Key,e.OptionalJsonValue,e.Visibility,e.Metadata.OccurredAtUtc)).ToList(),StateVersion=v.StateVersion+1 };
    public SessionExperienceView Apply(StoryMemoryRemoved e,SessionExperienceView v)=>v with { Memories=v.Memories.Where(x=>!(x.Scope==e.Scope&&x.ScopeId==e.ScopeId&&x.Key==e.Key)).ToList(),StateVersion=v.StateVersion+1 };
    public SessionExperienceView Apply(RelationshipChanged e,SessionExperienceView v)=>v with { Relationships=Upsert(v.Relationships,new(e.SourceEntityId,e.TargetEntityId,e.RelationshipKey,e.NewValue)),StateVersion=v.StateVersion+1 };
    public SessionExperienceView Apply(WorldNarrativePublished _,SessionExperienceView v)=>v with { StateVersion=v.StateVersion+1 };
    public SessionExperienceView Apply(ProposalSent e,SessionExperienceView v)=>Phase3ExperienceProjection.Apply(v,e);public SessionExperienceView Apply(ProposalCountered e,SessionExperienceView v)=>Phase3ExperienceProjection.Apply(v,e);public SessionExperienceView Apply(ProposalAccepted e,SessionExperienceView v)=>Phase3ExperienceProjection.Apply(v,e);public SessionExperienceView Apply(ProposalRejected e,SessionExperienceView v)=>Phase3ExperienceProjection.Apply(v,e);public SessionExperienceView Apply(ProposalCancelled e,SessionExperienceView v)=>Phase3ExperienceProjection.Apply(v,e);public SessionExperienceView Apply(ProposalExpired e,SessionExperienceView v)=>Phase3ExperienceProjection.Apply(v,e);
    public SessionExperienceView Apply(AgreementActivated e,SessionExperienceView v)=>Phase3ExperienceProjection.Apply(v,e);public SessionExperienceView Apply(AgreementExecuted e,SessionExperienceView v)=>Phase3ExperienceProjection.Apply(v,e);public SessionExperienceView Apply(AgreementFailed e,SessionExperienceView v)=>Phase3ExperienceProjection.Apply(v,e);public SessionExperienceView Apply(AuthoredBehaviorActionSelected e,SessionExperienceView v)=>Phase3ExperienceProjection.Apply(v,e);
    public SessionExperienceView Apply(ConsequenceScheduled e,SessionExperienceView v)=>Phase3ExperienceProjection.Apply(v,e);public SessionExperienceView Apply(ConsequenceTriggered e,SessionExperienceView v)=>Phase3ExperienceProjection.Apply(v,e);public SessionExperienceView Apply(ConsequenceCancelled e,SessionExperienceView v)=>Phase3ExperienceProjection.Apply(v,e);public SessionExperienceView Apply(ConsequenceFailed e,SessionExperienceView v)=>Phase3ExperienceProjection.Apply(v,e);
    private static IReadOnlyList<Metric> Upsert(IReadOnlyList<Metric> values,Metric value)=>values.Where(x=>!(x.Scope==value.Scope&&x.ScopeId==value.ScopeId&&x.MetricKey==value.MetricKey)).Append(value).ToList();
    private static IReadOnlyList<Relationship> Upsert(IReadOnlyList<Relationship> values,Relationship value)=>values.Where(x=>!(x.SourceEntityId==value.SourceEntityId&&x.TargetEntityId==value.TargetEntityId&&x.RelationshipKey==value.RelationshipKey)).Append(value).ToList();
}

internal static class Phase3ExperienceProjection
{
    public static SessionExperienceView Apply(SessionExperienceView v,ProposalSent e)=>v with { Proposals=(v.Proposals??[]).Append(new(e.ProposalId,v.Id,e.InteractionTypeId,e.SenderTeamId,e.ReceiverTeamId,e.CurrentRevisionNumber,ProposalStatus.Pending,e.CreatedAtCheckpointId,e.ValidUntilCheckpointId,e.CreatedAtStreamVersion)).ToList(),ProposalRevisions=(v.ProposalRevisions??[]).Append(new ProposalRevision(e.ProposalId,e.CurrentRevisionNumber,e.SenderTeamId,e.TermsPayload.Clone(),e.OfferedEffects,e.RequestedEffects,e.Metadata.OccurredAtUtc,e.CreatedAtStreamVersion)).ToList(),StateVersion=v.StateVersion+1 };
    public static SessionExperienceView Apply(SessionExperienceView v,ProposalCountered e)=>v with { Proposals=Proposal(v.Proposals,e.ProposalId,x=>x with { CurrentRevisionNumber=e.CurrentRevisionNumber,Status=ProposalStatus.Countered }),ProposalRevisions=(v.ProposalRevisions??[]).Append(new ProposalRevision(e.ProposalId,e.CurrentRevisionNumber,e.CreatedByTeamId,e.TermsPayload.Clone(),e.OfferedEffects,e.RequestedEffects,e.Metadata.OccurredAtUtc,e.CreatedAtStreamVersion)).ToList(),StateVersion=v.StateVersion+1 };
    public static SessionExperienceView Apply(SessionExperienceView v,ProposalAccepted e)=>v with { Proposals=Proposal(v.Proposals,e.ProposalId,x=>x with { Status=ProposalStatus.Accepted,AcceptedRevisionNumber=e.CurrentRevisionNumber,AgreementId=e.AgreementId }),StateVersion=v.StateVersion+1 };
    public static SessionExperienceView Apply(SessionExperienceView v,ProposalRejected e)=>Status(v,e.ProposalId,ProposalStatus.Rejected);public static SessionExperienceView Apply(SessionExperienceView v,ProposalCancelled e)=>Status(v,e.ProposalId,ProposalStatus.Cancelled);public static SessionExperienceView Apply(SessionExperienceView v,ProposalExpired e)=>Status(v,e.ProposalId,ProposalStatus.Expired);
    public static SessionExperienceView Apply(SessionExperienceView v,AgreementActivated e)=>v with { Agreements=(v.Agreements??[]).Append(new Agreement(e.AgreementId,e.ProposalId,e.AcceptedRevisionNumber,e.InteractionTypeId,e.PartyTeamIds,e.TermsPayload.Clone(),AgreementStatus.Active,e.ActivatedAtCheckpointId,null,null,e.Visibility)).ToList(),StateVersion=v.StateVersion+1 };
    public static SessionExperienceView Apply(SessionExperienceView v,AgreementExecuted e)=>v with { Agreements=Agreement(v.Agreements,e.AgreementId,x=>x with { Status=AgreementStatus.Executed,ExecutedAtCheckpointId=e.ExecutedAtCheckpointId }),Proposals=Proposal(v.Proposals,e.ProposalId,x=>x with { Status=ProposalStatus.Executed }),StateVersion=v.StateVersion+1 };
    public static SessionExperienceView Apply(SessionExperienceView v,AgreementFailed e)=>v with { Agreements=Agreement(v.Agreements,e.AgreementId,x=>x with { Status=AgreementStatus.Failed,FailedAtCheckpointId=e.FailedAtCheckpointId }),Proposals=Proposal(v.Proposals,e.ProposalId,x=>x with { Status=ProposalStatus.Failed }),StateVersion=v.StateVersion+1 };
    public static SessionExperienceView Apply(SessionExperienceView v,AuthoredBehaviorActionSelected e)=>v with { AuthoredBehaviorSelections=(v.AuthoredBehaviorSelections??[]).Append(new AuthoredBehaviorSelection(e.EntityId,e.BehaviorProfileId,e.RuleId,e.ActionId,e.DifficultyId,e.Metadata.CheckpointId??string.Empty,e.ResolutionNumber)).ToList(),StateVersion=v.StateVersion+1 };
    public static SessionExperienceView Apply(SessionExperienceView v,ConsequenceScheduled e)=>v with { ScheduledConsequences=(v.ScheduledConsequences??[]).Append(new ScheduledConsequence(e.ScheduledConsequenceId,e.DefinitionId,e.SourceEventId,e.SourceTeamId,e.SourceEntityId,e.ScheduledAtCheckpointId,e.DueCheckpointId,e.TriggerType,ScheduledConsequenceStatus.Pending,e.Visibility)).ToList(),StateVersion=v.StateVersion+1 };
    public static SessionExperienceView Apply(SessionExperienceView v,ConsequenceTriggered e)=>Consequence(v,e.ScheduledConsequenceId,ScheduledConsequenceStatus.Triggered);public static SessionExperienceView Apply(SessionExperienceView v,ConsequenceCancelled e)=>Consequence(v,e.ScheduledConsequenceId,ScheduledConsequenceStatus.Cancelled);public static SessionExperienceView Apply(SessionExperienceView v,ConsequenceFailed e)=>Consequence(v,e.ScheduledConsequenceId,ScheduledConsequenceStatus.Failed);
    private static SessionExperienceView Status(SessionExperienceView v,Guid id,ProposalStatus status)=>v with { Proposals=Proposal(v.Proposals,id,x=>x with { Status=status }),StateVersion=v.StateVersion+1 };
    private static SessionExperienceView Consequence(SessionExperienceView v,Guid id,ScheduledConsequenceStatus status)=>v with { ScheduledConsequences=(v.ScheduledConsequences??[]).Select(x=>x.ScheduledConsequenceId==id?x with { Status=status }:x).ToList(),StateVersion=v.StateVersion+1 };
    private static IReadOnlyList<Proposal> Proposal(IReadOnlyList<Proposal>? values,Guid id,Func<Proposal,Proposal> change)=>(values??[]).Select(x=>x.ProposalId==id?change(x):x).ToList();private static IReadOnlyList<Agreement> Agreement(IReadOnlyList<Agreement>? values,Guid id,Func<Agreement,Agreement> change)=>(values??[]).Select(x=>x.AgreementId==id?change(x):x).ToList();
}
