using System.Text.Json;
using FluentAssertions;
using Hambaft.Application;
using Hambaft.Domain;
using Hambaft.Infrastructure.StoryPackages;

namespace Hambaft.EndToEndTests;

public sealed class Phase3MultiplayerScenarioTests
{
    [Fact]
    public async Task Complete_phase3_multiplayer_flow_repeats_with_identical_fingerprint_and_rebuilds()
    {
        var first=await Run("standard");var second=await Run("standard");first.Fingerprint.Should().Be(second.Fingerprint);JsonSerializer.Serialize(first.State).Should().Be(JsonSerializer.Serialize(second.State));JsonSerializer.Serialize(StorySession.From(first.Events)).Should().Be(JsonSerializer.Serialize(first.State));
        first.State.CurrentCheckpointId.Should().Be("coordination-result");first.State.Proposals.Should().Contain(x=>x.Status==ProposalStatus.Executed).And.Contain(x=>x.Status==ProposalStatus.Expired);first.State.Agreements.Should().ContainSingle(x=>x.Status==AgreementStatus.Executed);first.State.ScheduledConsequences.Should().ContainSingle(x=>x.Status==ScheduledConsequenceStatus.Triggered);first.State.AuthoredBehaviorSelections.Should().HaveCount(2);first.State.Metrics.Single(x=>x.Scope==MetricScope.Entity&&x.ScopeId==SupplierEntity&&x.MetricKey=="entity.reliability").NumericValue.Should().Be(48);first.State.Metrics.Single(x=>x.Scope==MetricScope.Entity&&x.ScopeId==CarrierEntity&&x.MetricKey=="entity.capacity").NumericValue.Should().Be(65);first.State.Relationships.Single(x=>x.SourceEntityId==SupplierEntity&&x.TargetEntityId==CarrierEntity&&x.RelationshipKey=="relationship.trust").NumericValue.Should().Be(1);
        first.Supplier.Inbox!.Concat(first.Supplier.Outbox!).Should().OnlyContain(x=>x.SenderTeamId==SupplierTeam||x.ReceiverTeamId==SupplierTeam);first.Carrier.Inbox!.Concat(first.Carrier.Outbox!).Should().OnlyContain(x=>x.SenderTeamId==CarrierTeam||x.ReceiverTeamId==CarrierTeam);first.Public.PublicAgreements.Should().ContainSingle();first.Public.PublicConsequences.Should().ContainSingle();
    }

    [Fact]
    public async Task Hard_difficulty_changes_the_authored_behavior_action_for_same_seed_and_history_shape()
    {
        var standard=await Run("standard");var hard=await Run("hard");standard.State.Seed.Should().Be(hard.State.Seed);standard.State.ContentHash.Should().Be(hard.State.ContentHash);standard.State.AuthoredBehaviorSelections.Should().OnlyContain(x=>x.DifficultyId=="standard");hard.State.AuthoredBehaviorSelections.Should().OnlyContain(x=>x.DifficultyId=="hard");var package=await new FileSystemStoryPackageLoader(new StoryPackageOptions{Root=FindStories()},new DeterministicStoryPackageHasher(),new StoryPackageValidator()).LoadAsync("sample-cargo-delay","1.1.0",default);var hardDefinition=package.DifficultyDefinitions.Single(x=>x.Id=="hard");hardDefinition.BehaviorRuleWeightModifiers.Single(x=>x.RuleId=="opportunistic-credit-rule").Multiplier.Should().Be(3m);hardDefinition.BehaviorRuleWeightModifiers.Single(x=>x.RuleId=="cooperative-credit-rule").Multiplier.Should().Be(.5m);
    }

    private static async Task<Result> Run(string difficulty)
    {
        var hasher=new DeterministicStoryPackageHasher();var validator=new StoryPackageValidator();var loader=new FileSystemStoryPackageLoader(new StoryPackageOptions{Root=FindStories()},hasher,validator);var package=await loader.LoadAsync("sample-cargo-delay","1.1.0",default);var store=new MemoryStore();var runtime=new SessionRuntime(store,new FixedPairing(),loader,new DeterministicStoryletSelector(new ConditionEngine()),new EffectEngine(),new DeterministicBehaviorResolver(new ConditionEngine()));var commands=new Contexts();
        await runtime.ExecuteAsync(new CreateSession(Session,package.Manifest.Id,package.Manifest.Version,package.ContentHash,42,0,commands.Next(),difficulty),default);await runtime.ExecuteAsync(new AddTeam(Session,SupplierTeam,"Supplier",1,commands.Next()),default);await runtime.ExecuteAsync(new AddTeam(Session,CarrierTeam,"Carrier",2,commands.Next()),default);await runtime.ExecuteAsync(new CreateWorldEntity(Session,SupplierEntity,"supplier","Supplier",ControllerType.HumanTeam,null,3,commands.Next()),default);await runtime.ExecuteAsync(new CreateWorldEntity(Session,CarrierEntity,"carrier","Carrier",ControllerType.HumanTeam,null,4,commands.Next()),default);await runtime.ExecuteAsync(new CreateWorldEntity(Session,CreditEntity,"credit-provider","Credit Provider",ControllerType.AuthoredBehavior,"cooperative-credit",5,commands.Next()),default);await runtime.ExecuteAsync(new AssignEntityToTeam(Session,SupplierEntity,SupplierTeam,6,commands.Next()),default);await runtime.ExecuteAsync(new AssignEntityToTeam(Session,CarrierEntity,CarrierTeam,7,commands.Next()),default);await runtime.ExecuteAsync(new StartSession(Session,8,commands.Next()),default);var initialized=await runtime.ExecuteAsync(new InitializeNarrative(Session,9,commands.Next()),default);
        var state=StorySession.From(store.Events);var supplierAssignment=state.StoryletAssignments.Single(x=>x.StoryletId=="supplier-delay-response");var carrierAssignment=state.StoryletAssignments.Single(x=>x.StoryletId=="carrier-delay-response");var supplierChoice=await runtime.ExecuteAsync(new SubmitStoryChoice(Session,supplierAssignment.AssignmentId,"promise-original-deadline",initialized.StateVersion,commands.Next(SupplierTeam)),default);var carrierChoice=await runtime.ExecuteAsync(new SubmitStoryChoice(Session,carrierAssignment.AssignmentId,"reserve-emergency-capacity",supplierChoice.StateVersion,commands.Next(CarrierTeam)),default);
        var acceptedProposal=DeterministicIds.Create("phase3-e2e","accepted");var sent=await runtime.ExecuteAsync(new SendProposal(Session,acceptedProposal,"emergency-capacity-support",CarrierTeam,Terms(8,1,true),null,carrierChoice.StateVersion,commands.Next(SupplierTeam)),default);var countered=await runtime.ExecuteAsync(new CounterProposal(Session,acceptedProposal,1,Terms(12,2,false),sent.StateVersion,commands.Next(CarrierTeam)),default);var accepted=await runtime.ExecuteAsync(new AcceptProposal(Session,acceptedProposal,2,countered.StateVersion,commands.Next(SupplierTeam)),default);var unanswered=await runtime.ExecuteAsync(new SendProposal(Session,DeterministicIds.Create("phase3-e2e","unanswered"),"emergency-capacity-support",CarrierTeam,Terms(3,1,false),null,accepted.StateVersion,commands.Next(SupplierTeam)),default);
        var resolved=await runtime.ExecuteAsync(new ResolveNarrativeCheckpoint(Session,unanswered.StateVersion,commands.Next()),default);state=StorySession.From(store.Events);state.Proposals.Single(x=>x.ProposalId!=acceptedProposal).Status.Should().Be(ProposalStatus.Expired);state.Agreements.Single().Status.Should().Be(AgreementStatus.Executed);state.ScheduledConsequences.Should().ContainSingle(x=>x.Status==ScheduledConsequenceStatus.Pending);state.AuthoredBehaviorSelections.Should().ContainSingle();
        await runtime.ExecuteAsync(new ResolveNarrativeCheckpoint(Session,resolved.StateVersion,commands.Next()),default);state=StorySession.From(store.Events);var supplier=ViewProjector.Team(state,state.Teams.Single(x=>x.Id==SupplierTeam),package);var carrier=ViewProjector.Team(state,state.Teams.Single(x=>x.Id==CarrierTeam),package);var publicView=ViewProjector.Hydrate(ViewProjector.Public(state),package);ViewProjector.Session(state).StateVersion.Should().Be(state.StateVersion);return new(state,store.Events.ToList(),EventFingerprint.Compute(store.Events),supplier,carrier,publicView);
    }

    private static JsonElement Terms(decimal units,decimal duration,bool disclosure)=>JsonDocument.Parse($$"""{"capacityUnits":{{units}},"supportDurationCheckpoints":{{duration}},"publicDisclosure":{{disclosure.ToString().ToLowerInvariant()}}}""").RootElement.Clone();
    private static string FindStories(){var directory=new DirectoryInfo(AppContext.BaseDirectory);while(directory is not null&&!Directory.Exists(Path.Combine(directory.FullName,"stories")))directory=directory.Parent;return Path.Combine(directory!.FullName,"stories");}
    private static readonly Guid Session=Guid.Parse("12000000-0000-0000-0000-000000000001");private static readonly Guid SupplierTeam=Guid.Parse("22000000-0000-0000-0000-000000000001");private static readonly Guid CarrierTeam=Guid.Parse("22000000-0000-0000-0000-000000000002");private static readonly Guid SupplierEntity=Guid.Parse("32000000-0000-0000-0000-000000000001");private static readonly Guid CarrierEntity=Guid.Parse("32000000-0000-0000-0000-000000000002");private static readonly Guid CreditEntity=Guid.Parse("32000000-0000-0000-0000-000000000003");
    private sealed record Result(StorySession State,IReadOnlyList<IDomainEvent> Events,string Fingerprint,TeamExperienceView Supplier,TeamExperienceView Carrier,PublicWorldView Public);
    private sealed class Contexts{private int value;public CommandContext Next(Guid? team=null){var command=DeterministicIds.Create("phase3-e2e-command",++value);return new(Guid.Parse("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),command,command,team,new DateTimeOffset(2026,8,4,8,0,0,TimeSpan.Zero));}}
    private sealed class FixedPairing : IPairingCodeGenerator{public PairingCodeMaterial Generate()=>new("PAIRCODE","fixed-hash");public bool Verify(string rawCode,string persistedHash)=>true;}
    private sealed class MemoryStore : ISessionStore
    {
        public List<IDomainEvent> Events{get;}=[];public Task<StorySession?> LoadAsync(Guid id,CancellationToken ct)=>Task.FromResult(Events.Count==0?null:StorySession.From(Events));public Task<IReadOnlyList<IDomainEvent>> LoadEventsAsync(Guid id,CancellationToken ct)=>Task.FromResult<IReadOnlyList<IDomainEvent>>(Events.ToList());public Task AppendAsync(Guid id,long expected,IReadOnlyList<IDomainEvent> events,StorySession state,CancellationToken ct){if(expected!=Events.Count)throw new ConcurrencyConflictException(id,expected,Events.Count);Events.AddRange(events);return Task.CompletedTask;}public Task<SessionStateView?> LoadSessionViewAsync(Guid id,CancellationToken ct)=>Task.FromResult(Events.Count==0?null:ViewProjector.Session(StorySession.From(Events)));public Task<PublicWorldView?> LoadPublicViewAsync(Guid id,CancellationToken ct)=>Task.FromResult(Events.Count==0?null:ViewProjector.Public(StorySession.From(Events)));public Task<TeamExperienceView?> LoadTeamViewAsync(Guid id,CancellationToken ct){var state=StorySession.From(Events);var team=state.Teams.SingleOrDefault(x=>x.Id==id);return Task.FromResult(team is null?null:ViewProjector.Team(state,team));}
    }
}
