import { AssetId, type AssetManifest } from './assetRegistry'

/** Development-only manifest with neutral placeholder paths.
 *  Replace with production asset paths when final visuals arrive. */
export const devAssetManifest: Partial<AssetManifest> = {
  [AssetId.bazaarBase]: {
    src: '',
    width: 1200,
    height: 820,
    alpha: false,
    preload: 'high',
    label: 'پس‌زمینه بازار',
  },
  [AssetId.locationGate]: {
    src: '',
    width: 160,
    height: 140,
    alpha: true,
    preload: 'high',
    label: 'دروازه بازار',
  },
  [AssetId.locationChaharsoq]: {
    src: '',
    width: 200,
    height: 160,
    alpha: true,
    preload: 'high',
    label: 'چهارسوق',
  },
  [AssetId.locationHajSadeghOffice]: {
    src: '',
    width: 180,
    height: 200,
    alpha: true,
    preload: 'high',
    label: 'دفتر حاج صادق',
  },
  [AssetId.businessBakery]: {
    src: '',
    width: 160,
    height: 140,
    alpha: true,
    preload: 'high',
    label: 'نانوایی',
  },
  [AssetId.businessLogistics]: {
    src: '',
    width: 160,
    height: 140,
    alpha: true,
    preload: 'high',
    label: 'باربری',
  },
  [AssetId.businessPrinting]: {
    src: '',
    width: 160,
    height: 140,
    alpha: true,
    preload: 'high',
    label: 'چاپ',
  },
  [AssetId.businessExchange]: {
    src: '',
    width: 160,
    height: 140,
    alpha: true,
    preload: 'high',
    label: 'صرافی',
  },
  [AssetId.locationCaravanserai]: {
    src: '',
    width: 180,
    height: 150,
    alpha: true,
    preload: 'low',
    label: 'کاروانسرا',
  },
  [AssetId.investigationSeal]: {
    src: '',
    width: 80,
    height: 80,
    alpha: true,
    preload: 'high',
    label: 'مهر بررسی',
  },
  [AssetId.investigationSealSpent]: {
    src: '',
    width: 80,
    height: 80,
    alpha: true,
    preload: 'low',
    label: 'مهر مصرف‌شده',
  },
  [AssetId.proposalLetter]: {
    src: '',
    width: 600,
    height: 400,
    alpha: false,
    preload: 'low',
    label: 'نامه پیشنهاد',
  },
  [AssetId.agreementActive]: {
    src: '',
    width: 64,
    height: 64,
    alpha: true,
    preload: 'low',
    label: 'پیمان فعال',
  },
  [AssetId.overlayTrust]: {
    src: '',
    width: 32,
    height: 32,
    alpha: true,
    preload: 'low',
    label: 'اعتماد',
  },
  [AssetId.overlayObligation]: {
    src: '',
    width: 32,
    height: 32,
    alpha: true,
    preload: 'low',
    label: 'تعهد',
  },
  [AssetId.overlayDebt]: {
    src: '',
    width: 32,
    height: 32,
    alpha: true,
    preload: 'low',
    label: 'دین',
  },
  [AssetId.endingVeil]: {
    src: '',
    width: 1200,
    height: 820,
    alpha: true,
    preload: 'low',
    label: 'پرده پایان',
  },
}
