import { AssetId, type AssetManifest } from './assetRegistry'

const assetUrl = (name: string) => `/assets/hezar-cheragh/${name}`

/** Runtime manifest for the approved modular Hezar Cheragh candidates.
 *  Lighting, labels, selection, relationships and reactions remain code-owned. */
export const devAssetManifest: Partial<AssetManifest> = {
  [AssetId.bazaarBase]: {
    src: assetUrl('main-bazaar-street-segment.png'),
    width: 1254,
    height: 1254,
    alpha: true,
    preload: 'high',
    label: 'پس‌زمینه بازار',
  },
  [AssetId.locationGate]: {
    src: assetUrl('gate.png'),
    width: 1402,
    height: 1122,
    alpha: true,
    preload: 'high',
    label: 'دروازه بازار',
  },
  [AssetId.locationChaharsoq]: {
    src: assetUrl('chaharsoq.png'),
    width: 1402,
    height: 1122,
    alpha: true,
    preload: 'high',
    label: 'چهارسوق',
  },
  [AssetId.locationHajSadeghOffice]: {
    src: assetUrl('haj-sadegh-office.png'),
    width: 1402,
    height: 1122,
    alpha: true,
    preload: 'high',
    label: 'دفتر حاج صادق',
  },
  [AssetId.businessBakery]: {
    src: assetUrl('sepideh-bakery.png'),
    width: 1402,
    height: 1122,
    alpha: true,
    preload: 'high',
    label: 'نانوایی',
  },
  [AssetId.businessLogistics]: {
    src: assetUrl('rahe-no-logistics.png'),
    width: 1402,
    height: 1122,
    alpha: true,
    preload: 'high',
    label: 'باربری',
  },
  [AssetId.businessPrinting]: {
    src: assetUrl('roshan-printing-house.png'),
    width: 1536,
    height: 1024,
    alpha: true,
    preload: 'high',
    label: 'چاپ',
  },
  [AssetId.businessExchange]: {
    src: assetUrl('mizan-exchange.png'),
    width: 1254,
    height: 1254,
    alpha: true,
    preload: 'high',
    label: 'صرافی',
  },
  [AssetId.locationCaravanserai]: {
    src: assetUrl('courtyard-caravanserai.png'),
    width: 1402,
    height: 1122,
    alpha: true,
    preload: 'low',
    label: 'کاروانسرا',
  },
  [AssetId.investigationSeal]: {
    src: '',
    width: 80,
    height: 80,
    alpha: true,
    preload: 'high',
    label: 'مهر بررسی',
  },
  [AssetId.investigationSealSpent]: {
    src: '',
    width: 80,
    height: 80,
    alpha: true,
    preload: 'low',
    label: 'مهر مصرف‌شده',
  },
  [AssetId.proposalLetter]: {
    src: '',
    width: 600,
    height: 400,
    alpha: false,
    preload: 'low',
    label: 'نامه پیشنهاد',
  },
  [AssetId.agreementActive]: {
    src: '',
    width: 64,
    height: 64,
    alpha: true,
    preload: 'low',
    label: 'پیمان فعال',
  },
  [AssetId.overlayTrust]: {
    src: '',
    width: 32,
    height: 32,
    alpha: true,
    preload: 'low',
    label: 'اعتماد',
  },
  [AssetId.overlayObligation]: {
    src: '',
    width: 32,
    height: 32,
    alpha: true,
    preload: 'low',
    label: 'تعهد',
  },
  [AssetId.overlayDebt]: {
    src: '',
    width: 32,
    height: 32,
    alpha: true,
    preload: 'low',
    label: 'دین',
  },
  [AssetId.endingVeil]: {
    src: '',
    width: 1200,
    height: 820,
    alpha: true,
    preload: 'low',
    label: 'پرده پایان',
  },
}
